#!/usr/bin/env bash

# Update the package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Allow nginx HTTP
sudo ufw allow 'nginx HTTP'

# Create a default HTML file
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
service nginx restart

