#!/usr/bin/env bash

# Update the package index
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Allow nginx HTTP
sudo ufw allow 'Nginx HTTP'

# Create a default HTML file
sudo echo "Hello World!" > /var/www/html/index.html

# Restart Nginx
sudo service nginx restart