#!/usr/bin/env bash

# Update the package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Allow nginx HTTP
sudo ufw allow 'nginx HTTP'

# Create a default HTML file
echo "Hello World!" > /var/www/html/index.html

sed -i '/listen 80 defauly_server/a rewrite ^/redirect_me https://elgaily.com permanent;' /etc/nginx/sites-available/default

sed -i '/listen 80 defauly_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

