#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6

function install() {
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

server_config=\
"
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 521204-web-01 54.82.179.69:80 check
   server 521204-web-02 100.25.21.95:80 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

sudo service haproxy start
