#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
# Requirements:
# -Your Bash script must be 5 lines long or less
# -There must be a new line at the end of the file
# -You must respect usual Bash script requirements
# -You cannot use ;
# -You cannot use &&
# -You cannot use wget
# ..

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx start
sudo echo "" | sudo dd status=none of=/run/nginx.pid
