#!/usr/bin/env bash
# Using what you did for task #0, make your fix short and sweet.
# Requirements:
# -Your Bash script must be 5 lines long or less
# -There must be a new line at the end of the file
# -You must respect usual Bash script requirements
# -You cannot use ;
# -You cannot use &&
# -You cannot use wget
# -You cannot execute your previous answer file (Do not include the name of the previous script in this one)
# -service (init) must say that nginx is not running ← for real

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"
